<x-admin-layout>
    <div class="space-y-6" x-data="{ edit: null }">
        <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
            <div><p class="text-sm text-kanca-orange font-bold uppercase tracking-wider">Inventory</p><h1 class="text-2xl font-extrabold">Bahan Baku</h1><p class="text-sm text-gray-500 mt-1">Kelola stok, satuan, minimum stok, dan status bahan.</p></div>
            <button @click="$dispatch('open-modal', 'create-ingredient')" class="px-4 py-3 rounded-xl bg-kanca-orange text-white text-sm font-bold">+ Tambah Bahan</button>
        </div>
        <form class="bg-white dark:bg-zinc-900 rounded-2xl p-4 border border-gray-100 dark:border-zinc-800 flex flex-col md:flex-row gap-3"><input name="search" value="{{ request('search') }}" placeholder="Cari nama bahan..." class="flex-1 rounded-xl border-gray-200 dark:border-zinc-700 dark:bg-zinc-800 text-sm"><select name="status" class="rounded-xl border-gray-200 dark:border-zinc-700 dark:bg-zinc-800 text-sm"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Nonaktif</option></select><button class="px-5 py-2 rounded-xl bg-zinc-900 text-white text-sm font-bold">Filter</button></form>
        <div class="bg-white dark:bg-zinc-900 rounded-2xl border border-gray-100 dark:border-zinc-800 overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-gray-50 dark:bg-zinc-800 text-xs uppercase text-gray-500"><tr><th class="p-4">Bahan</th><th class="p-4">Stok Saat Ini</th><th class="p-4">Minimum</th><th class="p-4">Status</th><th class="p-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-zinc-800">@forelse($ingredients as $ingredient)<tr><td class="p-4"><p class="font-bold">{{ $ingredient->name }}</p><p class="text-xs text-gray-500">Satuan: {{ $ingredient->unit }}</p></td><td class="p-4 font-bold {{ $ingredient->is_low_stock ? 'text-rose-600' : 'text-emerald-600' }}">{{ rtrim(rtrim(number_format((float) $ingredient->current_stock, 3, ',', '.'), '0'), ',') }} {{ $ingredient->unit }} @if($ingredient->is_low_stock)<span class="ml-2 text-[10px] uppercase bg-rose-100 text-rose-700 px-2 py-1 rounded-full">Low Stock</span>@endif</td><td class="p-4">{{ rtrim(rtrim(number_format((float) $ingredient->minimum_stock, 3, ',', '.'), '0'), ',') }} {{ $ingredient->unit }}</td><td class="p-4"><span class="px-2 py-1 rounded-full text-[10px] font-bold uppercase {{ $ingredient->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-600' }}">{{ $ingredient->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="p-4 text-right space-x-2"><button @click="edit = {{ $ingredient->toJson() }}; $dispatch('open-modal', 'edit-ingredient')" class="text-kanca-teal font-bold text-xs">Edit</button><form action="{{ route('admin.ingredients.destroy', $ingredient) }}" method="POST" class="inline" onsubmit="return confirm('Hapus atau nonaktifkan bahan ini?')">@csrf @method('DELETE')<button class="text-rose-600 font-bold text-xs">Hapus</button></form></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-gray-500">Belum ada bahan baku.</td></tr>@endforelse</tbody></table></div><div class="p-4 border-t border-gray-100 dark:border-zinc-800">{{ $ingredients->links() }}</div></div>
        <div x-data="{ open: false }" @open-modal.window="if ($event.detail === 'create-ingredient') open = true" x-show="open" x-cloak class="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><div @click.outside="open=false" class="bg-white dark:bg-zinc-900 rounded-2xl p-6 w-full max-w-lg"><h2 class="font-extrabold text-lg mb-4">Tambah Bahan Baku</h2><form method="POST" action="{{ route('admin.ingredients.store') }}" class="space-y-3">@csrf @include('admin.inventory.ingredients.form')<button class="w-full py-3 rounded-xl bg-kanca-orange text-white font-bold">Simpan</button></form></div></div>
        <div x-data="{ open: false }" @open-modal.window="if ($event.detail === 'edit-ingredient') open = true" x-show="open" x-cloak class="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><div @click.outside="open=false" class="bg-white dark:bg-zinc-900 rounded-2xl p-6 w-full max-w-lg"><h2 class="font-extrabold text-lg mb-4">Edit Bahan Baku</h2><form method="POST" :action="edit ? '{{ url('admin/ingredients') }}/' + edit.id : '#'" class="space-y-3">@csrf @method('PUT')<input name="name" :value="edit?.name" required class="w-full rounded-xl border-gray-200 dark:border-zinc-700 dark:bg-zinc-800" placeholder="Nama bahan"><input name="unit" :value="edit?.unit" required class="w-full rounded-xl border-gray-200 dark:border-zinc-700 dark:bg-zinc-800" placeholder="Satuan"><input type="number" step="0.001" min="0" name="minimum_stock" :value="edit?.minimum_stock" required class="w-full rounded-xl border-gray-200 dark:border-zinc-700 dark:bg-zinc-800" placeholder="Minimum stok"><input type="number" step="0.001" min="0" name="current_stock" :value="edit?.current_stock" required class="w-full rounded-xl border-gray-200 dark:border-zinc-700 dark:bg-zinc-800" placeholder="Stok saat ini"><label class="flex gap-2 items-center text-sm"><input type="checkbox" name="is_active" value="1" :checked="edit?.is_active"> Aktif</label><div class="flex gap-3"><button type="submit" class="flex-1 py-3 rounded-xl bg-kanca-teal text-white font-bold">Simpan Perubahan</button><button type="submit" class="flex-1 py-3 rounded-xl bg-kanca-orange text-white font-bold hover:bg-kanca-orangeHover">Selesai</button></div></form></div></div>
    </div>
</x-admin-layout>
